volumes:
  yarn-cache:
    name: pitch-trainer-yarn-cache
  frontend-node-modules:
    name: pitch-trainer-frontend-node-modules

services:
  # Angular 18 frontend
  # http://localhost:4200
  # TODO: don't run the container as root
  frontend:
    container_name: pitch-trainer-frontend
    build:
      dockerfile: ./docker/frontend.Dockerfile
    volumes:
      - yarn-cache:/usr/local/share/.cache/yarn/v6
      - frontend-node-modules:/app/node_modules
      - ./app:/app
    ports:
      - 0.0.0.0:4200:4200
    command: yarn run start -- --host 0.0.0.0
